engines:
  eslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        - javascript
ratings:
  paths:
    - 'src/**.js'
exclude_paths:
  - 'test/**'
  - 'node_modules/**'
