sudo: false
language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - npm install
before_script:
  - npm dedupe
  - npm prune
script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "true" ] && npm run test'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run clean && npm run cover'
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run codeclimate && npm run semantic-release'
