sudo: false
language: node_js
node_js:
  - 8
#  - 7
#  - 6
#  - 5
os:
  - linux
#  - osx
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
    - /^greenkeeper/.*$/
  except:
    - gh-pages
script:
  - yarn run clean
  - yarn run eslint
  - yarn run cover
  - yarn run build
jobs:
  fast_finish: true
  include:
    - stage: release
      node_js: 8
#      before_install:
#        - git config --global user.name "$GH_USER_NAME"
#        - git config --global user.email "$GH_USER_EMAIL"
      script:
        - yarn run clean
        - yarn run eslint
        - yarn run cover
        - yarn run build
        - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
#            yarn run codeclimate;
            TRAVIS_JOB_NUMBER=WORKAROUND.1 npm run semantic-release;
#            yarn run jsdoc;
#            npm run gh-pages;
          else
            echo "Release stage is skipped on pull request.";
          fi
