sudo: false
language: node_js
node_js:
  - 8
#  - 7
#  - 6
#  - 5
os:
  - linux
  - osx
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
    - /^greenkeeper/.*$/
  except:
    - gh-pages
script:
  - yarn run clean
  - yarn run eslint
  - yarn run cover
  - yarn run build
jobs:
  fast_finish: true
  include:
    - stage: release
      node_js: 8
      before_install:
        - git config --global user.name "$GH_USER_NAME"
        - git config --global user.email "$GH_USER_EMAIL"
      script:
        - mkdir -p $TRAVIS_BUILD_DIR/.travis
        - touch $TRAVIS_BUILD_DIR/.travis/release.sh
        - chmod +x $TRAVIS_BUILD_DIR/.travis/release.sh
      before_deploy:
        - yarn run jsdoc
      deploy:
        - TRAVIS_JOB_NUMBER=WORKAROUND.1 yarn run semantic-release
      after_deploy:
        - yarn run codeclimate
        - yarn run gh-pages
      deploy:
        skip_cleanup: true
        provider: script
        script: $TRAVIS_BUILD_DIR/.travis/release.sh
        on:
          branch: master
