sudo: false
language: node_js
node_js:
  - 8
  - 7
  - 6
  - 5
os:
  - linux
  - osx
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
    - /^greenkeeper/.*$/
  except:
    - gh-pages
script: false
jobs:
  fast_finish: true
  include:
    - stage: Build
      script:
        - yarn run clean
        - yarn run eslint
        - yarn run cover
        - yarn run build
