language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - npm install
before_script:
  - npm run clean
script:
  - npm run cover
after_success:
  - npm run codeclimate
