sudo: false
language: node_js
node_js:
  - 8
  - 7
  - 6
  - 5
os:
  - linux
  - osx
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
    - /^greenkeeper/.*$/
  except:
    - gh-pages
script:
  - yarn run clean
  - yarn run eslint
  - yarn run cover
  - yarn run build
jobs:
  fast_finish: true
  include:
    - stage: release
      node_js: 8
      before_install:
        - git config --global user.name "$GH_USER_NAME"
        - git config --global user.email "$GH_USER_EMAIL"
      before_deploy:
        - yarn run jsdoc
      after_deploy:
        - yarn run codeclimate
        - yarn run gh-pages
      deploy:
        provider: script
        script: yarn run semantic-release
        on:
          branch: master
