sudo: false
language: node_js
node_js:
  - 8
  - 7
  - 6
  - 5
os:
  - linux
  - osx
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
    - /^greenkeeper/.*$/
  except:
    - gh-pages
jobs:
  include:
    - stage: Test
      node_js: 8
      script: yarn run clean
